---
- name: Add Docker CE repo (CentOS)
  yum_repository:
    description: Docker CE
    name: docker-ce
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable/
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
  when: ansible_distribution == "CentOS"

- name: Add Docker GPG key (Ubuntu)
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg
  when: ansible_distribution == "Ubuntu"

- name: Add Docker APT repository (Ubuntu)
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
  when: ansible_distribution == "Ubuntu"

- name: Install Docker CE
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Start Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Add vagrant user to docker group
  user:
    name: vagrant
    groups: docker
    append: yes
  
