---
- name: Deployment Testing
  hosts: deployment_test_hosts
  become: true
  roles:
    - role: docker_ce
      tags: [deployment_test_play, docker_ce_role]

- name: Webserver
  hosts: webserver_hosts
  become: true
  roles:
    - role: webserver
      tags: [webserver_play, webserver_role]

- name: Container Development
  hosts: container_devel_hosts
  become: true
  roles:
    - role: docker_ce
      tags: [container_devel_play, docker_ce_role]

    - role: k3d
      tags: [container_devel_play, k3d_role]

    - role: kubectl
      tags: [container_devel_play, kubectl_role]

