---
#- name: Webservers
#  hosts: webserver_hosts
#  become: true
#  roles:
#  - webservers

- name: Containers for Development
  hosts: container_devel_hosts
  become: true
  roles:
  - container-devel
